package com.glassait.androidproject.view.main;

import android.content.Context;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import androidx.fragment.app.Fragment;
import androidx.navigation.NavController;
import androidx.navigation.fragment.NavHostFragment;
import androidx.recyclerview.widget.GridLayoutManager;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import com.glassait.androidproject.R;
import com.glassait.androidproject.common.utils.secret.StoreLocalData;
import com.glassait.androidproject.model.dao.OfferDao;
import com.glassait.androidproject.model.database.AppDatabase;
import com.glassait.androidproject.model.database.Builder;
import com.glassait.androidproject.model.entity.Offer;
import com.glassait.androidproject.model.entity.User;

import java.util.List;

/**
 * A fragment representing a list of Items.
 * <p>
 * Code generated by Android Studio
 */
public class SeeAllOfferFragment extends Fragment {
    // Database part
    private static final AppDatabase mAppDatabase     = Builder.getInstance()
                                                               .getAppDatabase();
    private static final OfferDao    mOfferDao        = mAppDatabase.offerDao();
    // List part
    private static final String      ARG_COLUMN_COUNT = "column-count";
    private              int         mColumnCount     = 1;

    /**
     * Mandatory empty constructor for the fragment manager to instantiate the
     * fragment (e.g. upon screen orientation changes).
     */
    public SeeAllOfferFragment() {}

    @SuppressWarnings("unused")
    public static SeeAllOfferFragment newInstance(int columnCount) {
        SeeAllOfferFragment fragment = new SeeAllOfferFragment();
        Bundle              args     = new Bundle();
        args.putInt(
                ARG_COLUMN_COUNT,
                columnCount
        );
        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        if (getArguments() != null) {
            mColumnCount = getArguments().getInt(ARG_COLUMN_COUNT);
        }
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View root = inflater.inflate(
                R.layout.fragment_see_all_offer_list,
                container,
                false
        );

        NavController navController = NavHostFragment.findNavController(this);
        SecondActivity.getInstance()
                      .enableAddButton(v -> navController.navigate(R.id.create_offer_fragment));

        // Set the adapter
        if (root instanceof RecyclerView) {
            Context      context      = root.getContext();
            RecyclerView recyclerView = (RecyclerView) root;
            if (mColumnCount <= 1) {
                recyclerView.setLayoutManager(new LinearLayoutManager(context));
            } else {
                recyclerView.setLayoutManager(new GridLayoutManager(
                        context,
                        mColumnCount
                ));
            }

            List<Offer> offerList = null;
            String from = StoreLocalData.getInstance()
                                        .getSeeAll();
            User currentUser = StoreLocalData.getInstance()
                                             .getUser();

            if (from.equals("yourOffer")) {
                offerList = mOfferDao.getAllOffersFromCreatorId(currentUser.uid);
            } else if (from.equals("inArea")) {
                offerList = mOfferDao.getAllOffersNotReservedAndNotFromCreatorId(currentUser.uid);
            }

            SeeAllOfferRecyclerViewAdapter adapter = new SeeAllOfferRecyclerViewAdapter(offerList);
            adapter.setOnClickListener(offer -> {
                StoreLocalData.getInstance()
                              .setOffer(offer);
                navController.navigate(R.id.offer_fragment);
            });
            recyclerView.setAdapter(adapter);
        }
        return root;
    }

    @Override
    public void onStop() {
        super.onStop();
        SecondActivity.getInstance()
                      .disableAddButton();
    }
}