package com.glassait.androidproject.view.main;

import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.widget.TextView;

import androidx.annotation.NonNull;
import androidx.recyclerview.widget.RecyclerView;

import com.glassait.androidproject.databinding.FragmentSeeAllOfferBinding;
import com.glassait.androidproject.model.dao.OfferDao;
import com.glassait.androidproject.model.dao.UserDao;
import com.glassait.androidproject.model.database.AppDatabase;
import com.glassait.androidproject.model.database.Builder;
import com.glassait.androidproject.model.entity.Offer;
import com.glassait.androidproject.model.entity.User;

import java.util.List;

/**
 * {@link RecyclerView.Adapter} that can display a list {@link Offer}.
 * <p>
 * Code generated by Android Studio
 */
public class SeeAllOfferRecyclerViewAdapter
        extends RecyclerView.Adapter<SeeAllOfferRecyclerViewAdapter.ViewHolder> {
    // Database part
    private final  AppDatabase     mAppDatabase = Builder.getInstance()
                                                         .getAppDatabase();
    private final  UserDao         mUserDao     = mAppDatabase.userDao();
    private final  OfferDao        mOfferDao    = mAppDatabase.offerDao();
    // Adapter part
    private static List<Offer>     mList        = null;
    private static OnClickListener mListener;

    public SeeAllOfferRecyclerViewAdapter(List<Offer> offerList) {
        mList = offerList;
    }

    @NonNull
    @Override
    public ViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        return new ViewHolder(FragmentSeeAllOfferBinding.inflate(
                LayoutInflater.from(parent.getContext()),
                parent,
                false
        ));
    }

    @Override
    public void onBindViewHolder(final ViewHolder holder, int position) {
        holder.mItem = mList.get(position);
        holder.mTitleView.setText(mList.get(position).title);
        final User[] user = new User[1];

        mUserDao.getUserFromUid(mList.get(position).creatorId)
                .subscribe(
                        u -> user[0] = u,
                        throwable -> mOfferDao.delete(mList.get(position))
                )
                .dispose();

        String name = user[0].lastName + " " + user[0].firstName;
        holder.mNameView.setText(name);
        holder.mCityView.setText(user[0].address.getCity());
    }

    @Override
    public int getItemCount() {
        return mList.size();
    }

    public void setOnClickListener(OnClickListener listener) {
        mListener = listener;
    }

    public static class ViewHolder extends RecyclerView.ViewHolder {
        public final TextView mTitleView;
        public final TextView mNameView;
        public final TextView mCityView;
        public       Offer    mItem;

        public ViewHolder(FragmentSeeAllOfferBinding binding) {
            super(binding.getRoot());

            mTitleView = binding.titleOffer;
            mNameView = binding.nameOffer;
            mCityView = binding.cityOffer;

            binding.getRoot()
                   .setOnClickListener(v -> mListener.onClick(mList.get(getBindingAdapterPosition())));
        }
    }

    public interface OnClickListener {
        void onClick(Offer offer);
    }
}